export const script = 'script: (function() {'
  + 'if (document.cookie.includes(\'cookie_token_v2\') && document.cookie.includes(\'ltuid_v2\')) {'
  + 'const input = document.createElement(\'input\');'
  + 'input.value = document.cookie;'
  + 'document.body.appendChild(input);'
  + 'input.focus();'
  + 'input.select();'
  + 'var result = document.execCommand(\'copy\');'
  + 'document.body.removeChild(input);'
  + 'if (result) {'
  + 'alert(\'HoYoLAB cookie copied to clipboard\');'
  + '} else {'
  + 'prompt(\'Failed to copy cookie. Manually copy the cookie below:\n\n\', input.value);'
  + '}'
  + '} else {'
  + 'alert(\'Please logout and log back in. Cookie is expired/invalid!\');'
  + '}'
  + '})();'
